name: Publish master to DockerHub

on:
  workflow_run:
    workflows:
      - "Go Build & Test"
    branches:
      - "master"
    types:
      - "completed"

jobs:
  Publish_Docker_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Set Parameters
        id: params
        run: |
          echo "date=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_OUTPUT
          echo "shortRef=$(head -c 7 <<< '${{ github.sha }}')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: ./build/package/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: "alexswilliams/prom-trmnl-renderer:${{ github.ref_name }}--${{ steps.params.outputs.date }}--${{ steps.params.outputs.shortRef }}"
